In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/bank-customer-churn-prediction/Churn_Modelling.csv


In [2]:
data=pd.read_csv('/kaggle/input/bank-customer-churn-prediction/Churn_Modelling.csv')
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [79]:
newdata=data.drop(columns=['RowNumber','CustomerId','Surname','Gender','Tenure','HasCrCard'])
newdata

CreditScore Geography  Age    Balance  NumOfProducts  IsActiveMember  \
0             619    France   42       0.00              1               1   
1             608     Spain   41   83807.86              1               1   
2             502    France   42  159660.80              3               0   
3             699    France   39       0.00              2               0   
4             850     Spain   43  125510.82              1               1   
...           ...       ...  ...        ...            ...             ...   
9995          771    France   39       0.00              2               0   
9996          516    France   35   57369.61              1               1   
9997          709    France   36       0.00              1               1   
9998          772   Germany   42   75075.31              2               0   
9999          792    France   28  130142.79              1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 8 columns]

In [80]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
newdata['Geography']= label_encoder.fit_transform(newdata['Geography'])

newdata

CreditScore  Geography  Age    Balance  NumOfProducts  IsActiveMember  \
0             619          0   42       0.00              1               1   
1             608          2   41   83807.86              1               1   
2             502          0   42  159660.80              3               0   
3             699          0   39       0.00              2               0   
4             850          2   43  125510.82              1               1   
...           ...        ...  ...        ...            ...             ...   
9995          771          0   39       0.00              2               0   
9996          516          0   35   57369.61              1               1   
9997          709          0   36       0.00              1               1   
9998          772          1   42   75075.31              2               0   
9999          792          0   28  130142.79              1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 8 columns]

In [83]:
from sklearn.model_selection import train_test_split
x=newdata.drop(columns='Exited',axis=1)
y=newdata['Exited']
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2,random_state=40)

In [85]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import  classification_report,confusion_matrix

In [87]:
lr = LogisticRegression()
lr.fit(train_x ,train_y)
print("Model Score on Training data",lr.score(train_x ,train_y))
print("Model Score on Testing data",lr.score(test_x ,test_y))
y_pred = lr.predict(test_x)
print(classification_report(y_pred ,test_y))


confusion_matrix(test_y, y_pred)



Model Score on Training data 0.78775
Model Score on Testing data 0.799
              precision    recall  f1-score   support

           0       0.97      0.81      0.89      1936
           1       0.06      0.36      0.10        64

    accuracy                           0.80      2000
   macro avg       0.52      0.59      0.49      2000
weighted avg       0.95      0.80      0.86      2000



array([[1575,   41],
       [ 361,   23]])

In [90]:
rf=RandomForestClassifier()
rf.fit(train_x ,train_y)
print("Model Score on Training data",rf.score(train_x ,train_y))
print("Model Score on Testing data",rf.score(test_x ,test_y))
print(rf.feature_importances_,rf.feature_names_in_)
y_pred = rf.predict(test_x)
print(classification_report(y_pred ,test_y))


confusion_matrix(test_y, y_pred)

Model Score on Training data 0.999875
Model Score on Testing data 0.8665
[0.18637776 0.03576377 0.25444744 0.16508724 0.13346132 0.03705276
 0.18780971] ['CreditScore' 'Geography' 'Age' 'Balance' 'NumOfProducts'
 'IsActiveMember' 'EstimatedSalary']
              precision    recall  f1-score   support

           0       0.95      0.89      0.92      1719
           1       0.52      0.71      0.60       281

    accuracy                           0.87      2000
   macro avg       0.73      0.80      0.76      2000
weighted avg       0.89      0.87      0.87      2000



array([[1534,   82],
       [ 185,  199]])

In [89]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier()
gb.fit(train_x ,train_y)
print("Model Score on Training data",gb.score(train_x ,train_y))
print("Model Score on Testing data",gb.score(test_x ,test_y))
print(gb.feature_importances_)
y_pred = gb.predict(test_x)
print(classification_report(y_pred ,test_y))


confusion_matrix(test_y, y_pred)

Model Score on Training data 0.8675
Model Score on Testing data 0.878
[0.02525759 0.0407301  0.39829497 0.06823535 0.32574721 0.12058153
 0.02115326]
              precision    recall  f1-score   support

           0       0.97      0.89      0.93      1752
           1       0.51      0.78      0.61       248

    accuracy                           0.88      2000
   macro avg       0.74      0.84      0.77      2000
weighted avg       0.91      0.88      0.89      2000



array([[1562,   54],
       [ 190,  194]])